---
apiVersion: v1
kind: Template
metadata:
  labels:
    provider: fabric8
    project: fabric8-online-jenkins
    version: 1.0.66
    group: io.fabric8.online.packages
  name: fabric8-online-jenkins
objects:
- apiVersion: v1
  kind: ProjectRequest
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    labels:
      provider: fabric8
      project: fabric8-online-team
      version: 1.0.66
      group: io.fabric8.online.packages
    name: ${PROJECT_NAME}
- apiVersion: v1
  kind: RoleBindingRestriction
  metadata:
    name: dsaas-user-access
  spec: 
    userrestriction:
      users: 
      - ${PROJECT_USER}
- apiVersion: v1
  kind: RoleBinding
  metadata:
    labels:
      provider: fabric8
      project: fabric8-online-jenkins
      version: 1.0.66
      group: io.fabric8.online.packages
    name: useradmin
  roleRef:
    name: admin
  subjects:
  - kind: User
    name: ${PROJECT_USER}
  userNames:
  - ${PROJECT_USER}
