apiVersion: v1
kind: Template
metadata:
  name: f8tenant-config
  creationTimestamp: null
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8tenant
  type: Opaque
  data:
    postgres.host: bG9jYWxob3N0Cg==
    postgres.port: NTQzMgo=
    postgres.user: cG9zdGdyZXMK
    postgres.database: cG9zdGdyZXMK
    postgres.password: bXlzZWNyZXRwYXNzc3dvcmQK
    template.recommender.api.token: eHh4eA==
    service.account.id: YzIxMWYxYmQtMTdhNy00ZjhjLTlmODAtMDkxN2QxNjc4ODlk
    service.account.secret: dGVuYW50c2VjcmV0bmV3
    auth.token.key: dGVuYW50c2VjcmV0bmV3

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8tenant
  type: Opaque
  data:
    postgres.connection.maxidle: '30'
    postgres.connection.maxopen: '30'
    auth.url: https://auth.openshift.io
    cluster.refresh.delay: 1
    template.recommender.external.name: recommender.api.prod-preview.openshift.io
    template.domain: d800.free-int.openshiftapps.com
    template.che.multitenant.server: https://che.prod-preview.openshift.io
    template.jenkins.root.url: https://jenkins.prod-preview.openshift.io
